### ISSUE TITLE
Pytorch Geometric

### ISSUE THREAD

**Issue by anon767** [flyingdoog/PGExplainer_Pytorch#1]
Hi Flyingdoog,

good to see, that you are working on porting PGExplainer to Pytorch, however, I am wondering, are there any plans to integrate it into Pytorch Geometric?

Thanks in advance

**Comment by flyingdoog** [comment]
Thanks for the suggestion. I am still learning pytorch and I will try to integrate it to PyTorch Geometric when I finish the code.
